//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.SOAPService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SOAPService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MVC.SOAPService.CompositeType GetDataUsingDataContract(MVC.SOAPService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MVC.SOAPService.CompositeType> GetDataUsingDataContractAsync(MVC.SOAPService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        ApplicationService.DTOs.BookDTO[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooks", ReplyAction="http://tempuri.org/IService1/GetBooksResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookBySearch", ReplyAction="http://tempuri.org/IService1/GetBookBySearchResponse")]
        ApplicationService.DTOs.BookDTO[] GetBookBySearch(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookBySearch", ReplyAction="http://tempuri.org/IService1/GetBookBySearchResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO[]> GetBookBySearchAsync(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByID", ReplyAction="http://tempuri.org/IService1/GetBookByIDResponse")]
        ApplicationService.DTOs.BookDTO GetBookByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBookByID", ReplyAction="http://tempuri.org/IService1/GetBookByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO> GetBookByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutBook", ReplyAction="http://tempuri.org/IService1/PutBookResponse")]
        string PutBook(ApplicationService.DTOs.BookDTO bookDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutBook", ReplyAction="http://tempuri.org/IService1/PutBookResponse")]
        System.Threading.Tasks.Task<string> PutBookAsync(ApplicationService.DTOs.BookDTO bookDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBook", ReplyAction="http://tempuri.org/IService1/PostBookResponse")]
        string PostBook(ApplicationService.DTOs.BookDTO bookDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostBook", ReplyAction="http://tempuri.org/IService1/PostBookResponse")]
        System.Threading.Tasks.Task<string> PostBookAsync(ApplicationService.DTOs.BookDTO bookDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        string DeleteBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBook", ReplyAction="http://tempuri.org/IService1/DeleteBookResponse")]
        System.Threading.Tasks.Task<string> DeleteBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInfo", ReplyAction="http://tempuri.org/IService1/GetUserInfoResponse")]
        ApplicationService.DTOs.UserInfoDTO[] GetUserInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInfo", ReplyAction="http://tempuri.org/IService1/GetUserInfoResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserInfoDTO[]> GetUserInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        ApplicationService.DTOs.UserInfoDTO GetUserByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.UserInfoDTO> GetUserByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUserInfo", ReplyAction="http://tempuri.org/IService1/PutUserInfoResponse")]
        string PutUserInfo(ApplicationService.DTOs.UserInfoDTO userInfoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutUserInfo", ReplyAction="http://tempuri.org/IService1/PutUserInfoResponse")]
        System.Threading.Tasks.Task<string> PutUserInfoAsync(ApplicationService.DTOs.UserInfoDTO userInfoDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUserInfo", ReplyAction="http://tempuri.org/IService1/PostUserInfoResponse")]
        string PostUserInfo(ApplicationService.DTOs.UserInfoDTO userInfoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostUserInfo", ReplyAction="http://tempuri.org/IService1/PostUserInfoResponse")]
        System.Threading.Tasks.Task<string> PostUserInfoAsync(ApplicationService.DTOs.UserInfoDTO userInfoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserInfo", ReplyAction="http://tempuri.org/IService1/DeleteUserInfoResponse")]
        string DeleteUserInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserInfo", ReplyAction="http://tempuri.org/IService1/DeleteUserInfoResponse")]
        System.Threading.Tasks.Task<string> DeleteUserInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        ApplicationService.DTOs.CartDTO[] GetCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCart", ReplyAction="http://tempuri.org/IService1/GetCartResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.CartDTO[]> GetCartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartByID", ReplyAction="http://tempuri.org/IService1/GetCartByIDResponse")]
        ApplicationService.DTOs.CartDTO GetCartByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartByID", ReplyAction="http://tempuri.org/IService1/GetCartByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.CartDTO> GetCartByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutCart", ReplyAction="http://tempuri.org/IService1/PutCartResponse")]
        string PutCart(ApplicationService.DTOs.CartDTO cartDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PutCart", ReplyAction="http://tempuri.org/IService1/PutCartResponse")]
        System.Threading.Tasks.Task<string> PutCartAsync(ApplicationService.DTOs.CartDTO cartDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCart", ReplyAction="http://tempuri.org/IService1/PostCartResponse")]
        string PostCart(ApplicationService.DTOs.CartDTO bookDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostCart", ReplyAction="http://tempuri.org/IService1/PostCartResponse")]
        System.Threading.Tasks.Task<string> PostCartAsync(ApplicationService.DTOs.CartDTO bookDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCart", ReplyAction="http://tempuri.org/IService1/DeleteCartResponse")]
        string DeleteCart(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCart", ReplyAction="http://tempuri.org/IService1/DeleteCartResponse")]
        System.Threading.Tasks.Task<string> DeleteCartAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MVC.SOAPService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MVC.SOAPService.IService1>, MVC.SOAPService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MVC.SOAPService.CompositeType GetDataUsingDataContract(MVC.SOAPService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MVC.SOAPService.CompositeType> GetDataUsingDataContractAsync(MVC.SOAPService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ApplicationService.DTOs.BookDTO[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public ApplicationService.DTOs.BookDTO[] GetBookBySearch(string search) {
            return base.Channel.GetBookBySearch(search);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO[]> GetBookBySearchAsync(string search) {
            return base.Channel.GetBookBySearchAsync(search);
        }
        
        public ApplicationService.DTOs.BookDTO GetBookByID(int id) {
            return base.Channel.GetBookByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.BookDTO> GetBookByIDAsync(int id) {
            return base.Channel.GetBookByIDAsync(id);
        }
        
        public string PutBook(ApplicationService.DTOs.BookDTO bookDTO) {
            return base.Channel.PutBook(bookDTO);
        }
        
        public System.Threading.Tasks.Task<string> PutBookAsync(ApplicationService.DTOs.BookDTO bookDTO) {
            return base.Channel.PutBookAsync(bookDTO);
        }
        
        public string PostBook(ApplicationService.DTOs.BookDTO bookDto) {
            return base.Channel.PostBook(bookDto);
        }
        
        public System.Threading.Tasks.Task<string> PostBookAsync(ApplicationService.DTOs.BookDTO bookDto) {
            return base.Channel.PostBookAsync(bookDto);
        }
        
        public string DeleteBook(int id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBookAsync(int id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public ApplicationService.DTOs.UserInfoDTO[] GetUserInfo() {
            return base.Channel.GetUserInfo();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserInfoDTO[]> GetUserInfoAsync() {
            return base.Channel.GetUserInfoAsync();
        }
        
        public ApplicationService.DTOs.UserInfoDTO GetUserByID(int id) {
            return base.Channel.GetUserByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.UserInfoDTO> GetUserByIDAsync(int id) {
            return base.Channel.GetUserByIDAsync(id);
        }
        
        public string PutUserInfo(ApplicationService.DTOs.UserInfoDTO userInfoDTO) {
            return base.Channel.PutUserInfo(userInfoDTO);
        }
        
        public System.Threading.Tasks.Task<string> PutUserInfoAsync(ApplicationService.DTOs.UserInfoDTO userInfoDTO) {
            return base.Channel.PutUserInfoAsync(userInfoDTO);
        }
        
        public string PostUserInfo(ApplicationService.DTOs.UserInfoDTO userInfoDto) {
            return base.Channel.PostUserInfo(userInfoDto);
        }
        
        public System.Threading.Tasks.Task<string> PostUserInfoAsync(ApplicationService.DTOs.UserInfoDTO userInfoDto) {
            return base.Channel.PostUserInfoAsync(userInfoDto);
        }
        
        public string DeleteUserInfo(int id) {
            return base.Channel.DeleteUserInfo(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserInfoAsync(int id) {
            return base.Channel.DeleteUserInfoAsync(id);
        }
        
        public ApplicationService.DTOs.CartDTO[] GetCart() {
            return base.Channel.GetCart();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.CartDTO[]> GetCartAsync() {
            return base.Channel.GetCartAsync();
        }
        
        public ApplicationService.DTOs.CartDTO GetCartByID(int id) {
            return base.Channel.GetCartByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.CartDTO> GetCartByIDAsync(int id) {
            return base.Channel.GetCartByIDAsync(id);
        }
        
        public string PutCart(ApplicationService.DTOs.CartDTO cartDto) {
            return base.Channel.PutCart(cartDto);
        }
        
        public System.Threading.Tasks.Task<string> PutCartAsync(ApplicationService.DTOs.CartDTO cartDto) {
            return base.Channel.PutCartAsync(cartDto);
        }
        
        public string PostCart(ApplicationService.DTOs.CartDTO bookDto) {
            return base.Channel.PostCart(bookDto);
        }
        
        public System.Threading.Tasks.Task<string> PostCartAsync(ApplicationService.DTOs.CartDTO bookDto) {
            return base.Channel.PostCartAsync(bookDto);
        }
        
        public string DeleteCart(int id) {
            return base.Channel.DeleteCart(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCartAsync(int id) {
            return base.Channel.DeleteCartAsync(id);
        }
    }
}
